Repository elastic/ingest-docs, pull requests merged in 2023-09, with the labels that each got.

#379 Processor hints doc
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Labels: v8.10.0, backport-8.10

#447 Fix broken link to "Using a proxy server with Elastic Agent and Fleet"
  docs/en/ingest-arch/15-proxy.asciidoc
Labels: backport-8.10

#438 Add Fleet & Agent 7.17.13 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: Team:Docs, backport-skip

#392 Hintsbest practises
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/elastic-agent-kubernetes-autodiscovery.asciidoc
Labels: backport-8.9, backport-8.10

#439 Add Fleet & Agent 8.9.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
Labels: Team:Docs, backport-8.9, backport-8.10

#459 Add doc links to Fleet UI output settings descriptions
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.10

#461 Update the comparison table with Kafka support
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.10

#464 Move 8.9.0 RN host.name change to breaking changes section
  docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
Labels: Team:Elastic-Agent, backport-8.9, backport-8.10

#450 Add documentation for the `logs` command
  docs/en/ingest-management/commands.asciidoc
Labels: documentation, Team:Docs, Team:Elastic-Agent, backport-skip

#475 Fix breaking link in 8.10 troubleshooting docs to known issue 3375
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.10

#463 Adding information for NETINFO environmental variable
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: backport-skip

#433 Add 'Structure of a config file' for standalone agent and remove warnings
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/create-standalone-agent-policy.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-download.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, backport-8.10

#480 Fix IoC note in 8.10 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Labels: backport-8.10

#484 Fix `welcome-to-elastic` links
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: v8.9.0, backport-8.9, v8.10.0, backport-8.10

#488 Fix malformed link
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: documentation, backport-8.10

#494 [Backport] [8.9] [485] Update PGP key known issue
  docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
Labels: v8.9.0, backport-skip

#495 rename php to pgp in troubleshooting.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.9, backport-8.10

#437 Add tutorial: monitor nginx logs with standalone agent
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx.asciidoc
  docs/en/ingest-management/images/guide-add-agent-standalone01.png
  docs/en/ingest-management/images/guide-add-nginx-integration.png
  docs/en/ingest-management/images/guide-agent-logs-flowing.png
  docs/en/ingest-management/images/guide-agent-metrics-flowing.png
  docs/en/ingest-management/images/guide-agent-policies.png
  docs/en/ingest-management/images/guide-create-agent-policy.png
  docs/en/ingest-management/images/guide-create-first-deployment.png
  docs/en/ingest-management/images/guide-install-agent-on-host.png
  docs/en/ingest-management/images/guide-integrations-page.png
  docs/en/ingest-management/images/guide-nginx-browser-breakdown.png
  docs/en/ingest-management/images/guide-nginx-integration-added.png
  docs/en/ingest-management/images/guide-nginx-logs-dashboard.png
  docs/en/ingest-management/images/guide-nginx-policy.png
  docs/en/ingest-management/images/guide-nginx-welcome.png
  docs/en/ingest-management/images/guide-sign-up-trial.png
  docs/en/ingest-management/images/guide-system-metrics-dashboard.png
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, backport-8.10

#465 Add advanced YAML config for Fleet UI output settings docs
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.10

#510 Update Elastic Agent install docs to mention ARM binaries
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
Labels: backport-8.10

#509 Add Fleet & Agent 8.10.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Labels: backport-8.10

#513 Add links to the newly added standalone tutorial
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
Labels: backport-8.10

#479 Add option enrich none to input
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
Labels: backport-skip

#474 Add warning about quotation marks to Kafka output docs
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: Team:Docs, backport-8.10

#518 Remove beta tags from Fleet API Preview request
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: backport-8.10

#523 Add known issue and resolution for Fleet's KQL processing changes
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Labels: backport-8.10
