Repository elastic/ingest-docs, pull requests merged in 2023-12, with the labels that each got.

#725 [Backport] [main] [723] Update data-streams.asciidoc
  docs/en/ingest-management/data-streams.asciidoc
Labels: Team:Docs, backport

#735 Remove beta tag for translate_sid processor
  docs/en/ingest-management/processors/processor-translate_sid.asciidoc
Labels: backport-skip

#738 Fix below/above terms for troubleshooting page
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.11

#741 Adds 8.12 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#732 Add Fleet & Agent 7.17.16 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#731 Add Fleet & Agent 8.11.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11, backport-8.12

#749 Document presets for performance tuning to ES output
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12

#750 Update memory leak known issue to indicate all Beats are affected, updated workaround
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11, backport-8.12

#751 Add restriction that PowerShell ISE is not supported
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.11, backport-8.12

#764 Updating some of the data around the tuning presets
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12

#765 Remove external ES monitoring restriction
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12

#762 Document that remote ES service token can be stored as a secret
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.12

#696 Docs for secrets storage in agent outputs
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.12

#770 Add title to Performance Tuning EPS table
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12

#775 Update release notes with upgrade issues
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11, backport-8.12

#776 Updating the agent vs beats compatibility
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.12

#774 presets only apply to 8.12 and above agents
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12
