Repository elastic/ingest-docs, pull requests merged in 2023-08, with the labels that each got.

#375 IngestArch: Add port numbers to ea-es architectures
  docs/en/ingest-arch/images/ea-agent-installed.png
  docs/en/ingest-arch/images/ea-apis.png
Labels: documentation, backport-skip

#377 for connectivity to LS we need to have a cert defined
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.9

#380 Default container documentation backport
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Labels: backport-8.9

#396 Fixing typos in scaling-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: backport-8.9

#397 Fix images on Elastic Agent K8s Scaling page
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: Team:Docs, v8.9.0, backport-skip

#394 IngestArch: Add port numbers for ea-ls and ea-mq architectures and refine
  docs/en/ingest-arch/16-agent-kafka.asciidoc
  docs/en/ingest-arch/images/ea-apis.png
  docs/en/ingest-arch/images/ea-fs-proxy-es.png
  docs/en/ingest-arch/images/ea-kafka.png
  docs/en/ingest-arch/images/ea-ls-bridge.png
  docs/en/ingest-arch/images/ea-ls-enrich.png
  docs/en/ingest-arch/images/ea-ls-multi.png
  docs/en/ingest-arch/images/ea-lspq-es.png
  docs/en/ingest-arch/images/ea-proxy-fs-es.png
  docs/en/ingest-arch/images/ls-es.png
  docs/en/ingest-arch/images/ls-kafka-essink.png
Labels: backport-skip

#401 IngestArch: Update agent-installed graphic
  docs/en/ingest-arch/images/ea-agent-installed.png
Labels: documentation, backport-skip

#302 Comment about mTLS in ingst architecture for proxy.
  docs/en/ingest-arch/15-proxy.asciidoc
Labels: backport-8.9

#393 Update docs for diagnostic command
  docs/en/ingest-management/commands.asciidoc
Labels: Team:Elastic-Agent, backport-skip

#336 Add docs for Kafka output UI for Fleet managed agents
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/fleet/images/fleet-add-output-button.png
  docs/en/ingest-management/index.asciidoc
Labels: Team:Docs, backport-skip, v8.10.0

#411 IngestArch: Add images for air-gapped architectures
  docs/en/ingest-arch/images/ea-es-airgapped.png
  docs/en/ingest-arch/images/ea-ls-airgapped.png
Labels: documentation, IngestArch, backport-skip

#417 Adds tip about creating Elastic Defend policy using Fleet API
  docs/en/ingest-management/fleet/fleet-api-docs.asciidoc
Labels: Team:Docs, backport-8.9, backport-8.8

#420 Address feedback on Kafka output docs
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: Team:Docs, backport-skip, v8.10.0

#421 Small fixes for Kafka output docs
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: Team:Docs, backport-skip, v8.10.0

#422 Small fix to Fleet's Logstash output type
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: Team:Docs, backport-skip, v8.10.0

#428 Update mergify.yml for 8.10
  .mergify.yml
Labels: backport-skip

#416 Add docs for gomaxprops option
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: v8.10.0, backport-8.10

#431 Remove experimental tag and improve documentation of syslog processor
  docs/en/ingest-management/processors/processor-syslog.asciidoc
Labels: documentation, backport-skip
