Repository elastic/ingest-docs, pull requests merged in 2023-10, with the labels that each got.

#504 Add notes about asset installation on multiple spaces
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
Labels: backport-8.10

#528 Document migrating agents to a new cluster
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/migrate-elastic-agent.asciidoc
  docs/en/ingest-management/images/migrate-agent-agents-offline.png
  docs/en/ingest-management/images/migrate-agent-deployment-id.png
  docs/en/ingest-management/images/migrate-agent-elasticsearch-output.png
  docs/en/ingest-management/images/migrate-agent-fleet-server-host.png
  docs/en/ingest-management/images/migrate-agent-host-output-settings.png
  docs/en/ingest-management/images/migrate-agent-install-command-output.png
  docs/en/ingest-management/images/migrate-agent-install-command.png
  docs/en/ingest-management/images/migrate-agent-new-deployment.png
  docs/en/ingest-management/images/migrate-agent-newly-enrolled-agents.png
  docs/en/ingest-management/images/migrate-agent-policy-settings.png
  docs/en/ingest-management/images/migrate-agent-take-snapshot.png
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.10

#536 Update .backportrc.json with 8.11
  .backportrc.json
Labels: backport-skip

#535 Add 'fleet-server-port' parameter to agent install examples
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
Labels: backport-8.10, backport-8.11

#539 [8.11] Document migrating agents to a new cluster (#528)
  docs/en/ingest-management/fleet/fleet-manage-agents.asciidoc
  docs/en/ingest-management/fleet/migrate-elastic-agent.asciidoc
  docs/en/ingest-management/images/migrate-agent-agents-offline.png
  docs/en/ingest-management/images/migrate-agent-deployment-id.png
  docs/en/ingest-management/images/migrate-agent-elasticsearch-output.png
  docs/en/ingest-management/images/migrate-agent-fleet-server-host.png
  docs/en/ingest-management/images/migrate-agent-host-output-settings.png
  docs/en/ingest-management/images/migrate-agent-install-command-output.png
  docs/en/ingest-management/images/migrate-agent-install-command.png
  docs/en/ingest-management/images/migrate-agent-new-deployment.png
  docs/en/ingest-management/images/migrate-agent-newly-enrolled-agents.png
  docs/en/ingest-management/images/migrate-agent-policy-settings.png
  docs/en/ingest-management/images/migrate-agent-take-snapshot.png
  docs/en/ingest-management/index.asciidoc
Labels: backport

#544 Update screencapture to apply to agent policy
  docs/en/ingest-management/images/apply-agent-policy.png
Labels: backport-8.10, backport-8.11

#548 Fix agent details screencap on 'Migrate from Beats' page
  docs/en/ingest-management/images/migration-agent-data-streams.png
  docs/en/ingest-management/images/migration-agent-data-streams01.png
  docs/en/ingest-management/images/migration-agent-details.png
  docs/en/ingest-management/images/migration-agent-details01.png
  docs/en/ingest-management/images/migration-agent-status-healthy.png
  docs/en/ingest-management/images/migration-agent-status-healthy01.png
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
Labels: backport-8.10, backport-8.11

#557 Fix outdated Fleet Agents page screen captures
  docs/en/ingest-management/images/agent-status.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
Labels: backport-8.10, backport-8.11

#503 Updating doc for Hints Autodiscovery for multiple containers
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Labels: backport-skip

#562 Add docs for new 'Agent activity' UI
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/images/agent-activity.png
Labels: backport-8.10, backport-8.11

#563 Fix upgrading docs to match current UI
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/images/schedule-upgrade.png
  docs/en/ingest-management/images/upgrade-single-agent.png
  docs/en/ingest-management/images/upgrade-status.png
Labels: backport-8.10, backport-8.11

#552 Add Fleet & Agent 8.10.3 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.9.asciidoc
Labels: backport-8.10, backport-8.11

#553 Add Fleet & Agent 7.17.14 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#571 Add security issue to 8.10.3 docs
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Labels: backport-8.10, backport-8.11

#568 Add docs for agent upgrade restart feature
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-8.11

#561 Add list of Elastic Agent inputs for standalone configuration
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/inputs-list.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.10, backport-8.11

#532 Re-add docs for install '--base-path' parameter
  docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport-8.11

#516 Add Serverless restrictions to Fleet & Agent docs
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/fleet-server.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/serverless-restrictions.asciidoc
Labels: backport-8.10, backport-8.11

#590 Add known issue for Elastic Defend & Agent CPU spike bug
  docs/en/ingest-management/release-notes/release-notes-8.8.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.10, backport-8.11

#579 Add Fleet & Agent 8.10.4 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.10.asciidoc
Labels: backport-8.10, backport-8.11

#601 Un-single-source install and enroll command options
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.11

#599 Update the text around how much disk space is required by agent.
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.11

#604 Remove base-path option, temporarily
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.11

#609 Document required cooldown between restart attempts
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-skip

#607 Add install '--base-path' parameter to agent command reference
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.11

#611 Redirect troubleshooting for stuck agent upgrades
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.11

#613 Update screencap for agent monitoring
  docs/en/ingest-management/images/agent-status-filter.png
Labels: backport-8.10, backport-8.11

#577 [Hints Support] Update documentation for hints/host
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
Labels: backport-skip

#583 Add standalone agent config file example: Apache HTTP Server
  docs/en/ingest-management/elastic-agent/configuration/config
  docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-apache.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/examples/config-file-examples.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/structure-config-file.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.10, backport-8.11

#624 Fix code typo on Kubernetes autodiscover page
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
Labels: backport-8.10, backport-8.11

#632 Note that integrations list can be filtered by category
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
Labels: backport-8.10, backport-8.11
