Repository elastic/ingest-docs, pull requests merged in 2023-11, with the labels that each got.

#636 Reorganize and simplify Fleet Server docs
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server.asciidoc
  docs/en/ingest-management/fleet/deployment-models.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
  docs/en/ingest-management/redirects.asciidoc
Labels: backport-8.10, backport-8.11

#644 Remove obsolete 'deployment-models.asciidoc'
  docs/en/ingest-management/fleet/deployment-models.asciidoc
Labels: backport-8.10, backport-8.11

#630 Adding ingest docs information for k8s
  docs/en/ingest-management/elastic-agent/ingest-pipeline-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/images/add_resource_metadata.png
  docs/en/ingest-management/images/gsub_cronjob.png
  docs/en/ingest-management/images/gsub_deployment.png
  docs/en/ingest-management/images/ingest_pipeline_custom_k8s.png
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.10, backport-8.11, 8.11-request

#650 Move data streams into integrations section; reorder ToC
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.10, backport-8.11

#580 Add Fleet & Agent 8.11.0 Release Notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#657 Fix agent install path for macOS
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: backport-8.10, backport-8.11

#672 Change Serverless agent restriction to 10 thousand installs
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/overview.asciidoc
  docs/en/ingest-management/serverless-restrictions.asciidoc
Labels: backport-8.11

#674 Update Fleet/Agent docs for Agent tamper protection (Elastic Defend)
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/fleet.asciidoc
Labels: backport-8.11

#679 Add Fleet & Agent 7.17.15 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#681 Add Fleet & Agent 8.11.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#631 Update install-layout.asciidoc to reflect logging changes introduced in 8.6.0
  docs/en/ingest-management/tab-widgets/install-layout.asciidoc
Labels: documentation, backport, backport-8.11, 8.11-request

#684 Create CODEOWNERS file
  .github/CODEOWNERS
Labels: backport-skip

#689 Change CODEOWNERS to platform-docs
  .github/CODEOWNERS
Labels: backport-skip

#687 Update 8.11.0 and 8.11.1 Release Notes with upgrade issue workaround
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#685 Add compression_level setting to Fleet ES output page
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.11

#675 Add docs for new ingest pipeline extension points in Fleet
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-skip

#698 Update processor-add_kubernetes_metadata.asciidoc
  docs/en/ingest-management/processors/processor-add_kubernetes_metadata.asciidoc
Labels: backport-8.11

#701 Update Agent ID tip in 8.11 upgrade known issue
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#596 Document agent detailed upgrade states
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
  docs/en/ingest-management/images/upgrade-available-indicator.png
  docs/en/ingest-management/images/upgrade-detailed-state01.png
  docs/en/ingest-management/images/upgrade-detailed-state02.png
  docs/en/ingest-management/images/upgrade-non-detailed-old.png
  docs/en/ingest-management/images/upgrade-non-detailed.png
  docs/en/ingest-management/images/upgrade-states.png
Labels: backport-skip

#700 Document sending agent monitoring data to a remote Elasticsearch clsuter
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-skip

#710 Update integrations page with spaces warning
  docs/en/ingest-management/integrations/integrations.asciidoc
Labels: backport-skip

#714 Add known issue for PssFreeSnapshot memory leak
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#699 Update command reference docs
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.11

#712 Expand guidance for integrations and Kibana spaces
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
Labels: backport-8.11

#711 Update 8.11.1 Release Notes for upgrade issue
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#715 Disk queue: update agent compatibility (forward fit)
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-skip

#721 Add notice for Windows memory leak issue in 8.11.0 and 8.11.1 RN
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11

#723 Update data-streams.asciidoc
  docs/en/ingest-management/data-streams.asciidoc
Labels: Team:Docs

#728 Add GH action for posting docs preview
  .github/workflows/docs-preview.yml
Labels: backport-skip
