Repository elastic/ingest-docs, pull requests merged in 2024-10, with the labels that each got.

#1306 [Fleet/EA] Logstash & Kafka Outputs refresh
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.15

#1350 Add note about elliptic-curve restriction
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/mutual-tls.asciidoc
Labels: backport-8.15, backport-8.x

#1356 Update env variables for ES authentication
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: backport-skip

#1361 Add docs for advanced monitoring options
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.x

#1365 Update monitor-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x

#1368 Fix uninstall warning about current directory
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x

#1354 Add missing environment variables for container setup
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: backport-8.15, backport-8.x

#1374 [DOCS] Refine docs about EA > Kafka > LS > ES
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-8.15, backport-8.x

#1380 Add documentation in add_cloud_metadata processor about the usage of BEATS_ADD_CLOUD_METADATA_PROVIDERS env var
  docs/en/ingest-management/processors/processor-add_cloud_metadata.asciidoc
Labels: backport-8.x, 8.16-request

#1383 Add docs for 'delete unenrolled agents'
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.x

#1381 Add Fleet & Agent 8.15.3 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15, backport-8.x

#1389 Add note: integration-level outputs must be at same sub level
  docs/en/ingest-management/integrations/integration-level-outputs.asciidoc
Labels: backport-8.x

#1392 [main] Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/elastic-agent-kubernetes-autodiscovery.asciidoc
Labels: backport-skip

#1393 [8.x] Update elastic-agent-kubernetes-autodiscovery.asciidoc (#1391)
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/elastic-agent-kubernetes-autodiscovery.asciidoc
Labels: backport-skip

#1385 Add 8.16 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#1394 Add Fleet & Agent 7.17.25 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1403 Add known issue for 8.15.x memory increase.
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-skip, Team:Elastic-Agent-Data-Plane

#1407 Add the ability to backport to `main`
  .mergify.yml
Labels: backport-skip
