Repository elastic/ingest-docs, pull requests merged in 2024-07, with the labels that each got.

#1147 Change 'enable' to 'set up' for agent alerting
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.14

#1148 Remove sudo restriction from standalone examples
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-skip

#1149 Adds 8.15 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip, v8.15.0

#1151 Add escaping variable section.
  docs/en/ingest-management/elastic-agent/elastic-agent-variable-substitution.asciidoc
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#1141 Add Fleet & Agent 8.14.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
Labels: backport-8.14

#1132 Add mutual TLS docs
  docs/en/ingest-management/images/mutual-tls-cloud-proxy.png
  docs/en/ingest-management/images/mutual-tls-cloud.png
  docs/en/ingest-management/images/mutual-tls-fs-onprem-proxy.png
  docs/en/ingest-management/images/mutual-tls-fs-onprem.png
  docs/en/ingest-management/images/mutual-tls-on-prem.png
  docs/en/ingest-management/images/mutual-tls-onprem-advanced-yaml.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/generate-certificates.asciidoc
  docs/en/ingest-management/security/mutual-tls.asciidoc
Labels: backport-8.15

#1161 Use external link in files used in multiple books
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
Labels: backport-8.15

#1160 Add Fleet scaling recommendation: ES API key cache size
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-8.14, backport-8.15

#1154 Add read-only filesystem option for Elastic Agent on Docker
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/run-container-common/deploy-elastic-agent.asciidoc
Labels: backport-8.15

#1159 Add Fleet & Agent 8.14.3 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
Labels: backport-8.14, backport-8.15

#1168 Clarify EPR & Artifact registry requirement for Air Gapped
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.14, backport-8.15

#1155 Add best practices for using integration assets
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations-assets-best-practices.asciidoc
Labels: backport-8.14, backport-8.15

#1174 Data Streams: Add ecs@mappings disclaimer for index templates cloned on ES < 8.13
  docs/en/ingest-management/data-streams.asciidoc
Labels: enhancement, backport-8.13, backport-8.14

#1176 Add ECK deployment type with link to docs
  docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
Labels: backport-8.14, backport-8.15

#1173 Add docs for custom policy tagging
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/images/agent-policy-custom-field.png
Labels: backport-8.15

#1185 [DOCS] Update Fleet Server guide - Fleet Server keeps using the ES host provided at install/enroll time.
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Labels: backport-8.9, backport-8.8, backport-8.7, backport-7.17, backport-8.10, backport-8.11, backport-8.12, backport-8.13, backport-8.14, backport-8.15

#1205 Add `allow_older_versions` setting
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.14, backport-8.15

#1208 Add Fleet & Agent 7.17.23 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1214 [DOCS] Clarify cadence of updates to EPR image
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.14, backport-8.15
