Repository elastic/ingest-docs, pull requests merged in 2024-01, with the labels that each got.

#763 Document Fleet alerting
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.12

#780 Add missing action_limit settings and new policy_limit settings
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: Team:Fleet, backport-8.12

#786 Update 8.11.2 release notes with Fleet UI upgrade issue
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11, backport-8.12

#789 Add information about elastic agent diagnostics flow
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.11, backport-8.12

#794 Add details about custom upgrade version for agent
  docs/en/ingest-management/fleet/images/upgrade-agent-custom.png
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-skip

#796 Improve agent uninstall docs to ensure correct directory
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
Labels: backport-8.11, backport-8.12

#799 Add Fleet & Agent 8.11.4 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.11.asciidoc
Labels: backport-8.11, backport-8.12

#654 Doc: Add structure and content for air-gapped architectures
  docs/en/ingest-arch/20-airgap.asciidoc
  docs/en/ingest-arch/99-airgapped.asciidoc
  docs/en/ingest-arch/99a-airgapped-ea-es.asciidoc
  docs/en/ingest-arch/99b-airgapped-ea-ls.asciidoc
  docs/en/ingest-arch/arch-list.asciidoc
  docs/en/ingest-arch/images/ea-airgapped.png
  docs/en/ingest-arch/index.asciidoc
Labels: backport-8.11, backport-8.12

#806 Update output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
Labels: backport-8.12

#809 Add troubleshooting for TSDB runtime issue
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.11, backport-8.12

#813 Document Fleet isAirGapped setting
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-skip

#818 Remove duplicate restrictions from agent install page
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.11, backport-8.12

#773 Add Fleet & Agent 8.12.0 Release Notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#826 Make the agent upgrade tracking change more obvious and link directly to the docs
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#817 Fix kubernetes provider documentation
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
Labels: backport-skip

#815 Add troubleshooting note for removed Fleet Server integration
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.12

#828 Add link to 'communications amongst components' diagram
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-8.12

#822 Add details about agent namespaces cascading to integration policies
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-skip

#816 Add agent mTLS flags
  docs/en/ingest-management/commands.asciidoc
Labels: backport-skip

#834 Regex support of add_resource_metadata
  docs/en/ingest-management/elastic-agent/configuration/providers/kubernetes-provider.asciidoc
  docs/en/ingest-management/processors/processor-add_kubernetes_metadata.asciidoc
Labels: backport-8.12

#802 Adding page for advance agent configuration with k8s
  docs/en/ingest-management/elastic-agent/advanced-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/images/k8skibanaUI.png
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.11, backport-8.12

#833 Add Fleet & Agent 7.17.17 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#843 Remove the restriction on Remote ES that says we can't send data to it.
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-8.12

#840 Document possible collisions with '@custom ingest pipelines'
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#850 Add docs to configure remote ES output
  docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.12

#847 Add instructions to prepare remote clusters with integration assets
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.12

#851 Update breaking change for pipelines
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#842 Add troubleshooting for Agent Out of Memory on K8s
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.12

#856 Update title for Fleet settings section
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.12

#859 Document memory queue configuration
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.12

#865 Add known issue for AWS S3 performance regression in 8.12
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: Team:Elastic-Agent, backport-8.12

#870 Expand/fix custom presets docs
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-output-logstash.asciidoc
Labels: backport-8.12

#868 Add required roles and privileges for Fleet & Integrations
  docs/en/ingest-management/fleet/fleet.asciidoc
  docs/en/ingest-management/images/kibana-fleet-privileges.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/fleet-roles-and-privileges.asciidoc
Labels: backport-8.12
