Repository elastic/ingest-docs, pull requests merged in 2024-11, with the labels that each got.

#1416 Update docs version of reference.yml and improve header section
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
Labels: backport-8.x, backport-8.16

#1413 Add documentation for elastic-agent-cert-key-passphrase option
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/mutual-tls.asciidoc
  docs/en/ingest-management/security/tls-overview.asciidoc
Labels: backport-8.x, 8.16-request, backport-8.16

#1428 Add a note about the agent status table limit of 10k records
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1430 Move section about Logstash to bottom of Kafka output page
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1330 Add ECS known issue for ecs@mappings and fieldless searches
  docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1349 Clarification of MSI Upgrading Behavior
  docs/en/ingest-management/elastic-agent/install-agent-msi.asciidoc
Labels: backport-8.x, backport-8.16, backport-main

#1375 Add docs for installing agent using Helm
  docs/en/ingest-management/elastic-agent/example-kubernetes-fleet-managed-agent-helm.asciidoc
  docs/en/ingest-management/elastic-agent/example-kubernetes-standalone-agent-helm.asciidoc
  docs/en/ingest-management/elastic-agent/images/helm-example-fleet-metrics-dashboard.png
  docs/en/ingest-management/elastic-agent/images/helm-example-nodes-enrollment-confirmation.png
  docs/en/ingest-management/elastic-agent/images/helm-example-nodes-logs-and-metrics.png
  docs/en/ingest-management/elastic-agent/images/helm-example-nodes-metrics-dashboard.png
  docs/en/ingest-management/elastic-agent/images/helm-example-pods-metrics-dashboard.png
  docs/en/ingest-management/elastic-agent/install-on-kubernetes-using-helm.asciidoc
  docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.x, backport-8.16

#1445 Update Kafka Output settings documentation to indicate minimum version value for Kafka 4.0
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1414 Update the elastic-agent resource consumption docs
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: documentation, backport-skip

#1452 Wording tweak to agent resource requirements table
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1412 Add Fleet & Agent 8.16.0 Release Notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16

#1417 Add Fleet & Agent 8.15.4 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1453 Update size on disk figures for Elastic Agent
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1464 Fix link to 8.15.x memory queue issue in Beats.
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16

#1467 Upgrading MSI installation
  docs/en/ingest-management/elastic-agent/install-agent-msi.asciidoc
Labels: backport-8.x, backport-8.16

#1465 Update bulk_reassign_agents_request to include batchSize body parameter
  docs/en/ingest-management/fleet/api-generated/rules/fleet-apis-passthru.asciidoc
Labels: backport-8.x, backport-8.16

#1457 Update output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
Labels: backport-main

#1488 Add 8.17 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#1486 Add Fleet & Agent 8.16.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16

#1492 Add mention of reusable integration policies
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1496 Add Fleet & Agent 8.15.5 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15, backport-8.x, backport-8.16, backport-8.17

#1504 Fixed very small typo in air-gapped.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-main

#1507 Add Fleet & Agent 7.17.26 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip
