Repository elastic/ingest-docs, pull requests merged in 2024-08, with the labels that each got.

#1221 Update air-gapped install docs wrt ARM64
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-skip

#1219 Remove warning about Fleet Server using ES host at install/enroll time
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Labels: backport-8.15

#1226 [DOCS] Update link
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.14, backport-8.15

#1201 Add Fleet & Agent 8.15.0 Release Notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15

#1241 Add technical preview tag for agent unprivileged mode
  docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
Labels: backport-8.15

#1245 Add note to 'unprivleged' agent docs about elastic-agent-user
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
Labels: backport-8.15

#1249 Fix screenshots for agent policies view in Nginx guides
  docs/en/ingest-management/images/guide-agent-policies.png
Labels: backport-8.15

#1223 Add known issue for 7.17.23 to 8.14/8.15 upgrade
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1247 Update 'logs flowing' screenshots in Nginx tutorials
  docs/en/ingest-management/images/guide-agent-logs-flowing.png
Labels: backport-8.15

#1248 Fix outdated dashboard screencap in Nginx guides
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
  docs/en/ingest-management/images/guide-agent-metrics-flowing.png
Labels: backport-8.15

#1218 Add docs for integrations-level outputs
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integration-level-outputs.asciidoc
Labels: backport-skip

#1246 Fix screenshots for Nginx integration, diagnostics, & failed upgrades docs
  docs/en/ingest-management/images/agent-set-logging-level.png
  docs/en/ingest-management/images/guide-integrations-page.png
  docs/en/ingest-management/images/upgrade-failure.png
Labels: backport-8.15

#1256 [main] [DOCS] Warn about sensible information in Elastic Agent diagnostic (#1255)
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport

#1260 Document list of auto-updated packages
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
Labels: backport-8.15

#1250 Add docs for agent 'otel' mode
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.15

#1259 Add docs for agent unenrollment timeout setting
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport-skip

#1264 Update docs for reusable integrations policies
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: backport-skip

#1267 Add CA rotation docs
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates-rotation.asciidoc
  docs/en/ingest-management/security/images/certificate-rotation-agent-es.png
Labels: backport-8.15
