Repository elastic/ingest-docs, pull requests merged in 2024-04, with the labels that each got.

#993 Add missing step to edit integration policy namespace
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-8.13

#992 Add Fleet & Agent 8.13.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Labels: backport-8.13

#996 Simplify step to open Fleet for compatibility with Serverless
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/install-fleet-managed-elastic-agent.asciidoc
  docs/en/ingest-management/fleet-agent-proxy-managed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
  docs/en/ingest-management/fleet/fleet-server-monitoring.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
  docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/upgrade-integration.asciidoc
  docs/en/ingest-management/integrations/view-integration-assets.asciidoc
  docs/en/ingest-management/integrations/view-integration-policies.asciidoc
  docs/en/ingest-management/migrate-beats-to-agent.asciidoc
  docs/en/ingest-management/serverless-restrictions.asciidoc
  docs/en/ingest-management/tab-widgets/add-fleet-server/content.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.13

#990 Configure kubernetes metadata enrichment
  docs/en/ingest-management/elastic-agent/configuring-kubernetes-metadata.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent-in-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/images/kubernetes_metadata.png
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.13

#1012 QA fix: deployment-id capture on migrate agents page
  docs/en/ingest-management/images/migrate-agent-deployment-id.png
Labels: backport-8.13

#1009 QA fix: diagnostics tab in logs screenshot
  docs/en/ingest-management/images/view-agent-logs.png
Labels: backport-8.13

#1008 QA fix: edit output flyout screenshot
  docs/en/ingest-management/images/elastic-agent-proxy-edit-output.png
Labels: backport-8.13

#1010 QA fix: screenshots on beats agent compatibility page
  docs/en/ingest-management/images/agent-monitoring-assets.png
  docs/en/ingest-management/images/agent-monitoring-settings.png
Labels: backport-8.13

#1011 QA fix: integrations capture on fleet overview page
  docs/en/ingest-management/images/integrations.png
Labels: backport-8.13

#1019 QA fix: Update agent actions menu screencaps
  docs/en/ingest-management/images/add-remove-tags.png
  docs/en/ingest-management/images/agent-tags.png
  docs/en/ingest-management/images/apply-agent-policy.png
  docs/en/ingest-management/images/schedule-upgrade.png
  docs/en/ingest-management/images/upgrade-single-agent.png
Labels: backport-8.13

#1021 Fix screencaps missing uninstall token tab
  docs/en/ingest-management/elastic-agent/run-container-common/kibana-fleet-data.asciidoc
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/images/agent-status.png
  docs/en/ingest-management/images/agent-status1.png
  docs/en/ingest-management/images/kibana-fleet-agents-overview.png
  docs/en/ingest-management/images/kibana-fleet-agents.png
  docs/en/ingest-management/images/kibana-fleet-datastreams.png
  docs/en/ingest-management/images/migrate-agent-agents-offline.png
  docs/en/ingest-management/images/migrate-agent-fleet-server-host.png
  docs/en/ingest-management/images/migrate-agent-host-output-settings.png
  docs/en/ingest-management/images/migrate-agent-newly-enrolled-agents.png
  docs/en/ingest-management/images/migration-agent-data-streams01.png
  docs/en/ingest-management/images/migration-agent-details01.png
  docs/en/ingest-management/images/migration-agent-status-healthy01.png
  docs/en/ingest-management/images/upgrade-single-agent.png
  docs/en/ingest-management/overview.asciidoc
Labels: backport-8.13

#1025 Update overview with link to general Adding Data to ES docs
  docs/en/ingest-management/overview.asciidoc
Labels: backport-8.13

#1028 Add known issue for MSI binary installs
  docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Labels: backport-8.13

#1030 Update 8.12.2 release notes for MSI slash issue
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-skip

#1034 Add docs for Fleet Server with multiple ES hosts
  docs/en/ingest-management/fleet/fleet-server-multiple-hosts.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip

#1037 Adds 8.14 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#1039 Add docs for MSI install
  docs/en/ingest-management/elastic-agent/install-agent-msi.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.14

#1038 Add considerations for changing outputs in a policy
  docs/en/ingest-management/fleet/fleet-settings-changing-outputs.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.13, backport-8.14

#1043 Fix incorrect 'Agents tab' reference in Fleet Server setup
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
Labels: backport-8.13, backport-8.14
