Repository elastic/ingest-docs, pull requests merged in 2024-02, with the labels that each got.

#860 Add missing options for Elastic Agent 'enroll' and 'install' commands
  docs/en/ingest-management/commands.asciidoc
Labels: backport-skip

#876 Add Kafka output settings to standalone agent docs
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
Labels: backport-8.12

#874 Add details about info shared, via proxy, with the EPR
  docs/en/ingest-management/fleet-agent-proxy-package-registry.asciidoc
Labels: backport-8.12

#883 Add Fleet & Agent 7.17.18 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#864 Add Fleet & Agent 8.12.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#884 Update providers_default_disable
  docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
Labels: backport-skip

#863 Update ingest pipeline docs with new integrations pattern naming
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-8.12

#889 Update serverless restrictions wrt proxy support
  docs/en/ingest-management/serverless-restrictions.asciidoc
Labels: backport-skip

#892 Remove Fleet Server policy_limit settings
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-8.12

#899 Add ToC to troubleshooting docs
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.12

#894 Expand and make more prominent integrations multi-space limitations
  docs/en/ingest-management/integrations/install-integration-assets.asciidoc
Labels: backport-8.12

#896 Add performance tuning presets to standalone agent docs
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
Labels: backport-8.12

#903 Add troubleshooting for agent that can't be unenrolled
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.12

#895 Deprecate the fleet-server policy_throttle, use action_limit instead.
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-skip

#908 Add known issue for stuck agent upgrade (8.12.0, 8.12.1)
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#909 Small fixes for API keys docs
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Labels: backport-8.12

#915 [DOCS] Fix Elastic Agent input examples
  docs/en/ingest-management/security/logstash-certificates.asciidoc
Labels: backport-8.12

#906 Add tutorial for standalone agent on serverless monitoring nginx
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.12

#918 Fix known issue for stuck upgrade in 8.12.1 release notes
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12

#920 Add 8.13 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#923 Fix migrate integrations docs
  docs/en/ingest-management/fleet/migrate-elastic-agent.asciidoc
Labels: backport-8.12, backport-8.13

#924 Fix examples to use API key authentication
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-debug-input-configs.asciidoc
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Labels: backport-8.12, backport-8.13

#929 Document that disk queues cannot be configured for Agent-managed Beats
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: documentation, Team:Docs, Team:Elastic-Agent, backport-skip

#930 Remove nonexistent option from enroll command
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.12, backport-8.13

#932 [main] Remove nonexistent option from enroll command (#930)
  docs/en/ingest-management/commands.asciidoc
Labels: backport-skip

#921 Adding info for conditions for autodiscovery
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-conditions-autodiscover.asciidoc
Labels: backport-8.11, backport-8.12

#934 Update air-gapped.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-skip

#941 [main] Update air-gapped.asciidoc (#934)
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-skip

#935 Update Elastic-Agent Kafka settings
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
Labels: Team:Elastic-Agent, backport-skip

#943 Remove processors settings from Kafka output docs
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-skip

#939 Add Fleet & Agent 8.12.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12, backport-8.13
