Repository elastic/ingest-docs, pull requests merged in 2024-06, with the labels that each got.

#1097 Remove 'technical preview' warning from FQDN docs
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-features.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-skip

#1090 Add note about '/liveness' endpoint for standalone agent
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport-skip

#1111 Add missing number signs for Fleet Server Release Notes links
  docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
Labels: backport-8.14

#1100 Fix liveness endpoint docs
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-monitoring.asciidoc
Labels: backport-skip

#1113 Proxy docs: Update caps and remove technical preview banner
  docs/en/ingest-management/fleet-agent-proxy-managed.asciidoc
  docs/en/ingest-management/images/elastic-agent-proxy-edit-agent-binary-source.png
  docs/en/ingest-management/images/elastic-agent-proxy-edit-fleet-server.png
  docs/en/ingest-management/images/elastic-agent-proxy-edit-output.png
  docs/en/ingest-management/images/elastic-agent-proxy-edit-proxy.png
Labels: backport-skip

#1116 Add 'Elastic Agent health status' page
  docs/en/ingest-management/fleet/agent-health-status.asciidoc
  docs/en/ingest-management/fleet/images/agent-health-status.png
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.14

#1119 Add links at top of FAQ page
  docs/en/ingest-management/troubleshooting/faq.asciidoc
Labels: backport-8.14

#1094 Add Fleet & Agent 7.17.22 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1121 Add license
  LICENSE
  README.md
Labels: backport-7.17, backport-8.14

#489 Add logging configuration example to the Configure inputs page
  docs/en/ingest-management/elastic-agent/configuration/inputs/input-configuration.asciidoc
Labels: backport-8.14

#1127 Add steps to create an alert based on agent status
  docs/en/ingest-management/fleet/images/elastic-agent-status-rule.png
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
Labels: backport-8.14

#1053 Add Elastic-Agent event log documentation
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/tab-widgets/logging.asciidoc
Labels: Team:Elastic-Agent, backport-skip

#1126 Add Fleet & Agent 8.14.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.14.asciidoc
Labels: backport-8.14

#1099 Add mTLS flags to 'Configure SSL/TLS' docs
  docs/en/ingest-management/security/certificates.asciidoc
Labels: backport-8.14

#1092 Move Agent policy settings docs to correct location
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/fleet/fleet-settings.asciidoc
Labels: backport-8.14

#1138 Fix 'API key' link to point to Fleet & Agent instructions
  docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-apache.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/examples/config-file-example-nginx.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-ess.asciidoc
  docs/en/ingest-management/elastic-agent/example-standalone-monitor-nginx-serverless.asciidoc
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Labels: backport-8.14

#1087 Add steps and details for running 'unprivileged' Elastic Agent
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
  docs/en/ingest-management/images/integration-root-requirement.png
  docs/en/ingest-management/images/privileged-and-unprivileged-agents.png
  docs/en/ingest-management/images/root-integration-and-unprivileged-agents.png
  docs/en/ingest-management/images/unprivileged-agent-warning.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/tab-widgets/download.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-skip

#1145 Fix Serverless variable in API key steps
  docs/en/ingest-management/elastic-agent/grant-access-to-elasticsearch.asciidoc
Labels: backport-8.14
