Repository elastic/ingest-docs, pull requests merged in 2024-12, with the labels that each got.

#1505 Add docs for running unprivileged agent as existing user/group
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
Labels: backport-8.x

#1483 Add known issues for 'no agent found', Agent uninstall exception
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1514 Use correct technical preview tags
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.x

#1520 Fix Elastic-Agent event logger documentation
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/tab-widgets/event-logging-widget.asciidoc
  docs/en/ingest-management/tab-widgets/event-logging.asciidoc
Labels: Team:Elastic-Agent-Data-Plane, backport-8.15, backport-8.x, backport-8.16, backport-8.17

#1498 Add Fleet & Agent 8.17.0 Release Notes
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.x, backport-8.17

#1510 Add agent upgrade steps for DEB & RPM
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1545 Fix typo in filestream docs link
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-main

#1537 Fix version compatibility statement
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Labels: backport-8.x, backport-8.17

#1544 Add download steps for Wolfi container images
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1550 Add placeholder for 'transform to OTel Collector' docs
  docs/en/ingest-management/elastic-agent/otel-agent-transform.asciidoc
  docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.x

#1538 Add Fleet & Agent 8.16.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1563 Update policy scaling recommendation
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/fleet/fleet-server-scaling.asciidoc
Labels: backport-8.x

#1572 Add small doc about running a standalone agent in otel mode
  docs/en/ingest-management/elastic-agent/otel-agent-transform.asciidoc
Labels: backport-8.x

#1573 Update troubleshooting.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-main
