Repository elastic/ingest-docs, pull requests merged in 2024-03, with the labels that each got.

#956 [main] Update fleet-settings-output-kafka.asciidoc (#953)
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-skip

#962 Add custom settings page
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/override-policy-settings.asciidoc
Labels: backport-8.12, backport-8.13

#967 Update troubleshooting.asciidoc to fix 'syntethic' typo
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.12, backport-8.13

#971 Add restrictions to agent upgrade docs
  docs/en/ingest-management/fleet/upgrade-elastic-agent.asciidoc
Labels: backport-skip

#973 Scrub book-level attributes from Fleet & Agent guide
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/elastic-agent-standalone-logging.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/inputs/simplified-input-configuration.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/install-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/installation-layout.asciidoc
  docs/en/ingest-management/elastic-agent/start-stop-elastic-agent.asciidoc
  docs/en/ingest-management/elastic-agent/uninstall-elastic-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
  docs/en/ingest-management/integrations/edit-or-delete-integration-policy.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-8.13

#976 Remove key:value spaces from Kafka processors doc
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-skip

#977 Update scaling-on-kubernetes.asciidoc
  docs/en/ingest-management/elastic-agent/scaling-on-kubernetes.asciidoc
Labels: backport-skip

#963 Add Fleet & Agent 7.17.19 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#981 [Fleet] Add variable to the preconfiguration example
  docs/en/ingest-management/create-agent-policies-no-UI.asciidoc
Labels: Team:Fleet, backport-skip

#970 [DOCS] Fleet managed integrations content
  docs/en/ingest-management/images/system-managed.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/integrations/integrations.asciidoc
  docs/en/ingest-management/integrations/managed-integrations-content.asciidoc
Labels: documentation, Team:Docs, backport-skip, 8.13-request

#983 Update 8.13.0 queue documentation and release notes
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-elasticsearch.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-kafka.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-shared-settings.asciidoc
  docs/en/ingest-management/release-notes/release-notes-8.13.asciidoc
Labels: Team:Docs, Team:Elastic-Agent, backport-8.13

#986 Remove tech preview notice from Kafka output docs
  docs/en/ingest-management/fleet/fleet-settings-output-kafka.asciidoc
Labels: backport-8.13
