Repository elastic/ingest-docs, pull requests merged in 2024-09, with the labels that each got.

#1276 Update port assignments from 'Fleet' to 'Kibana (Fleet)'
  docs/en/ingest-management/fleet/add-fleet-server-cloud.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-mixed.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Labels: backport-8.15

#1280 Add supported TLS version info to air-gapped docs
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.15

#1278 Add Fleet & Agent 8.15.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15

#1274 Remove 'fleet-server-insecure-http' setting from docs
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/container-envs.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/env/shared-env.asciidoc
Labels: backport-8.15

#1292 Add release notes for elastic/kibana#191730
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15

#1294 Update 8.12 Release Notes for Remote ES / Elastic Defend bug
  docs/en/ingest-management/release-notes/release-notes-8.12.asciidoc
Labels: backport-8.12, backport-8.13, backport-8.14, backport-8.15

#1288 Fix agent status docs for unhealthy status
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/images/agent-status-diagram.png
Labels: backport-8.15

#1285 Add section about Env Provider availability for Fleet-managed agent
  docs/en/ingest-management/agent-policies-environment-variables.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.15

#1290 Add Fleet & Agent 7.17.24 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1295 Fix up enrollment token docs
  docs/en/ingest-management/security/enrollment-tokens.asciidoc
Labels: backport-8.15

#1305 Document format for air-gapped downloadable packages
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.15

#1309 Correct incorrect connection_idle_timeout setting
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: documentation, Team:Docs

#1310 [main] Correct incorrect connection_idle_timeout setting (#1309)
  docs/en/ingest-management/fleet/fleet-settings-output-elasticsearch.asciidoc
Labels: backport-skip

#1311 Add 8.x branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip

#1312 Add known issue that Beats do not recover from transient network errors
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: Team:Docs, backport-8.15

#1315 [Fleet & Agent docs] Change 'beats' namespace to 'elastic-agent'
  docs/en/ingest-management/elastic-agent/advanced-kubernetes-managed-by-fleet.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/autodiscovery/kubernetes-hints-autodiscover.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/fleet/filter-agent-list-by-tags.asciidoc
  docs/en/ingest-management/fleet/fleet-server-secrets.asciidoc
  docs/en/ingest-management/tab-widgets/run-agent-image/content.asciidoc
Labels: backport-8.15, backport-8.x

#1316 Update beats-agent-comparison.asciidoc
  docs/en/ingest-management/beats-agent-comparison.asciidoc
Labels: backport-8.15, backport-8.x

#1322 Change docker link from 'beats' to 'elastic-agent' namespace
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/run-container-common/download-elastic-agent.asciidoc
Labels: backport-8.15, backport-8.x

#1296 Add docs for orphaned integrations
  docs/en/ingest-management/agent-policies.asciidoc
  docs/en/ingest-management/integrations/add-integration-to-policy.asciidoc
Labels: backport-8.x

#1324 Add page summarizing one-way and mutual TLS connections flow
  docs/en/ingest-management/images/tls-overview-mutual-all.jpg
  docs/en/ingest-management/images/tls-overview-mutual-fs-agent.png
  docs/en/ingest-management/images/tls-overview-mutual-fs-es.png
  docs/en/ingest-management/images/tls-overview-oneway-all.jpg
  docs/en/ingest-management/images/tls-overview-oneway-fs-agent.png
  docs/en/ingest-management/images/tls-overview-oneway-fs-es.png
  docs/en/ingest-management/index.asciidoc
  docs/en/ingest-management/security/certificates.asciidoc
  docs/en/ingest-management/security/mutual-tls.asciidoc
  docs/en/ingest-management/security/tls-overview.asciidoc
Labels: backport-8.15, backport-8.x

#1184 Add Fleet Server install steps on K8s and Docker
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-managed-by-fleet.asciidoc
Labels: backport-8.15, backport-8.x

#1334 Add 'Docker and Kubernetes' to Deployment Models page
  docs/en/ingest-management/fleet/fleet-deployment-models.asciidoc
Labels: backport-8.15, backport-8.x

#1335 Add new data stream type custom component template to Fleet docs
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-8.x

#1341 Remove technical preview markers for 'unprivileged' mode
  docs/en/ingest-management/commands.asciidoc
  docs/en/ingest-management/elastic-agent/elastic-agent-unprivileged-mode.asciidoc
Labels: backport-8.x

#1340 Add Fleet & Agent 8.15.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.15.asciidoc
Labels: backport-8.15, backport-8.x

#1344 Fix standalone agent K8s manifest link to include patch level
  docs/en/ingest-management/elastic-agent/running-on-kubernetes-standalone.asciidoc
Labels: backport-8.15, backport-8.x

#1351 Add restriction about containerized agent on Windows
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport-8.15, backport-8.x
