Repository elastic/ingest-docs, pull requests merged in 2025-03, with the labels that each got.

#1711 Add Fleet & Agent 8.16.5 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.16, backport-8.17, backport-8.18

#1709 Add Fleet & Agent 8.17.3 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.17, backport-8.18

#1720 Revert "[8.17] Update Fleet docs for new 'read' access roles (backport #1697)"
  docs/en/ingest-management/images/kibana-fleet-privileges-all.png
  docs/en/ingest-management/images/kibana-fleet-privileges-read.png
  docs/en/ingest-management/security/fleet-roles-and-privileges.asciidoc
Labels: backport-skip

#1722 Update fleet-agent-proxy-package-registry.asciidoc
  docs/en/ingest-management/fleet-agent-proxy-package-registry.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1731 Add tip about dynamic inputs to install page
  docs/en/ingest-management/elastic-agent/install-elastic-agent.asciidoc
Labels: backport-8.18

#1739 Add Fleet & Agent 8.16.6 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.16, backport-8.17, backport-8.18
