Repository elastic/ingest-docs, pull requests merged in 2025-02, with the labels that each got.

#1669 Add Fleet & Agent 8.16.4 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17, backport-8.18

#1670 Add Fleet & Agent 8.17.2 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1672 Add known issue for Kibana OOM crashes
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1684 Typo fix in air-gapped.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.15, backport-8.16

#1668 [Elastic-Agent] Remove flag --non-interactive from the enroll documentation
  docs/en/ingest-management/commands.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1667 [DOCS] Warn LS pipeline should not modify fields coming from EA
  docs/en/ingest-management/elastic-agent/configuration/outputs/output-logstash.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1687 Add Fleet & Agent 7.17.28 Release Notes
  docs/en/ingest-management/release-notes/release-notes-7.17.asciidoc
Labels: backport-skip

#1697 Update Fleet docs for new 'read' access roles
  docs/en/ingest-management/images/kibana-fleet-privileges-all.png
  docs/en/ingest-management/images/kibana-fleet-privileges-read.png
  docs/en/ingest-management/security/fleet-roles-and-privileges.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18

#1704 Fix link in 8.17.2 release notes
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.x, backport-8.17, backport-8.18
