Repository elastic/ingest-docs, pull requests merged in 2025-01, with the labels that each got.

#1578 Fix typo in k8s standalone agent example
  docs/en/ingest-management/elastic-agent/example-kubernetes-standalone-agent-helm.asciidoc
Labels: backport-8.x, backport-8.17

#1579 Enable new agent -> OTel-agent transform docs
  docs/en/ingest-management/elastic-agent/otel-agent.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-skip

#1581 Fix screenshot: 1231
  docs/en/ingest-management/images/download-agent-policy.png
Labels: backport-8.x, backport-8.17

#1582 Fix screenshot: 1232
  docs/en/ingest-management/images/guide-agent-policies.png
Labels: backport-8.x, backport-8.17

#1583 Fix screenshot: 1233
  docs/en/ingest-management/images/migration-add-nginx-integration.png
Labels: backport-8.x, backport-8.17

#1586 Fix screenshot: 1237
  docs/en/ingest-management/images/kibana-agent-flyout.png
Labels: backport-8.x, backport-8.17

#1587 Fix steps and screencap for agent diagnostics: 1238
  docs/en/ingest-management/fleet/images/collect-agent-diagnostics.png
  docs/en/ingest-management/fleet/images/collect-agent-diagnostics1.png
  docs/en/ingest-management/fleet/images/collect-agent-diagnostics2.png
  docs/en/ingest-management/fleet/monitor-elastic-agent.asciidoc
  docs/en/ingest-management/troubleshooting/troubleshooting.asciidoc
Labels: backport-skip

#1585 Fix screenshot: 1234
  docs/en/ingest-management/images/data-stream-info.png
Labels: backport-8.x, backport-8.17

#1588 Fix screenshot: 1239
  docs/en/ingest-management/fleet/images/fleet-server-configuration.png
Labels: backport-8.x, backport-8.17

#1609 Remove TLSv1.0 from supported protocols
  docs/en/ingest-management/elastic-agent/configuration/authentication/ssl-settings.asciidoc
  docs/en/ingest-management/elastic-agent/configuration/yaml/elastic-agent-reference-yaml.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#1610 Add details for Wolfi install image
  docs/en/ingest-management/elastic-agent/elastic-agent-container.asciidoc
Labels: backport-8.x, backport-8.17

#1615 known issue for when an integration level output is set to default
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1627 Explain why Agent needs to connect to Kibana
  docs/en/ingest-management/fleet/add-fleet-server-on-prem.asciidoc
Labels: backport-8.x, backport-8.17

#1623 Update data streams ILM tutorials and associated warnings
  docs/en/ingest-management/data-streams.asciidoc
  docs/en/ingest-management/images/component-templates-list.png
  docs/en/ingest-management/images/data-stream-overview.png
  docs/en/ingest-management/images/index-template-system-auth.png
  docs/en/ingest-management/images/review-component-template01.png
  docs/en/ingest-management/images/review-component-template02.png
  docs/en/ingest-management/integrations/integrations-assets-best-practices.asciidoc
Labels: backport-8.x, backport-8.17

#1530 Update docs to indicate that providers are no longer enabled by default
  docs/en/ingest-management/elastic-agent/configuration/providers/elastic-agent-providers.asciidoc
Labels: backport-8.x

#1614 Add Fleet & Agent 8.16.3 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.16.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#1612 Add Fleet & Agent 8.17.1 Release Notes
  docs/en/ingest-management/release-notes/release-notes-8.17.asciidoc
Labels: backport-8.x, backport-8.17

#1622 Add restrictions for synthetic `_source`
  docs/en/ingest-management/data-streams.asciidoc
Labels: backport-8.x, backport-8.17

#1639 Add warning about Elastic Defend with remote ES output
  docs/en/ingest-management/fleet/fleet-settings-remote-elasticsearch.asciidoc
Labels: backport-8.x, backport-8.17

#1645 [Reusable integration] GA on 8.16 requires Enterprise License
  docs/en/ingest-management/agent-policies.asciidoc
Labels: backport-8.16, backport-8.17

#1644 Doc: Add content for Ingest Overview
  docs/en/ingest-arch/index.asciidoc
  docs/en/ingest-guide/index.asciidoc
  docs/en/ingest-guide/ingest-additional-proc.asciidoc
  docs/en/ingest-guide/ingest-faq.asciidoc
  docs/en/ingest-guide/ingest-intro.asciidoc
  docs/en/ingest-guide/ingest-solutions.asciidoc
  docs/en/ingest-guide/ingest-static.asciidoc
  docs/en/ingest-guide/ingest-timestamped.asciidoc
  docs/en/ingest-guide/ingest-tools.asciidoc
Labels: backport-skip

#1518 Fleet Server on kubernetes document proposal
  docs/en/ingest-management/fleet/add-fleet-server-kubernetes-content.asciidoc
  docs/en/ingest-management/fleet/add-fleet-server-kubernetes.asciidoc
  docs/en/ingest-management/index.asciidoc
Labels: backport-8.x, backport-8.16, backport-8.17

#984 Add steps to configure a PGP key for agent upgrade
  docs/en/ingest-management/elastic-agent/upgrade-standalone-elastic-agent.asciidoc
  docs/en/ingest-management/fleet/air-gapped.asciidoc
Labels: backport-8.x, backport-8.17

#1658 --fleet-server-cert-key-passphrase-path -> --fleet-server-cert-key-passphrase
  docs/en/ingest-management/fleet/fleet-server-secrets.asciidoc
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.17

#1648 github-action: Add AsciiDoc freeze warning
  .github/workflows/comment-on-asciidoc-changes.yml
Labels: backport-skip

#1664 Add 8.18 branch to backport and mergify configs
  .backportrc.json
  .mergify.yml
Labels: backport-skip
